defaults:
  - override hydra/launcher: joblib  # Parallel runs

seed: -1
debug: False
exp_name: "NCP-GMM-C2"
exp_label: "test"
patience: 40
truncated_op_bias: 'Cxy'  # 'Cxy' or 'diagCxy' or 'svals'

model: NCP
gamma: 1e-2        # Weight of the NCP regularization loss term. NCP train best at low gamma values < 0.01
lr: 5e-4           # Learning rate NCP train best at low lr values < 1e-3
batch_size: 2024   # The higher the best
max_epochs: 1000   # Number of passes over ${gmm.n_samples} before stop training. Early stopping is used.

gmm:
  n_kernels: 2
  n_samples: 10000
  seed: 10  # Seed for the reproducibility of the GMM dataset

embedding:
  hidden_units: 32
  hidden_layers: 2
  embedding_dim: 14
  activation: GELU

embedding_desc: "hu${embedding.hidden_units}_hl${embedding.hidden_layers}_ed${embedding.embedding_dim}_act${embedding.activation}"
gmm_desc: "nk${gmm.n_kernels}_ns${gmm.n_samples}"
model_desc: "${model}_gamma${gamma}_lr${lr}_bs${batch_size}_me${max_epochs}"

hydra:
  run:
    #  ${hydra.job.override_dirname} Puts the override values in the directory name
    dir: "../experiments/${exp_name}/${exp_label}/${gmm_desc}/${model_desc}--${embedding_desc}/${hydra.job.override_dirname} seed=${seed}"

  sweep:
    dir: ./experiments/${exp_name}/${exp_label}/${gmm_desc}/
    subdir: ${model_desc}--${embedding_desc}/${hydra.job.override_dirname} seed=${seed}

  job:
    name: ${exp_name}
    num: ${seed}
    env_set:
      HYDRA_FULL_ERROR: '1'
      WANDB_START_METHOD: 'thread'
    config:
      override_dirname:
        kv_sep: "="
        item_sep: " "
        exclude_keys:
          - debug
          - seed
          - exp_name
          - exp_label
          - max_epochs
          - embedding.hidden_units
          - embedding.hidden_layers
          - embedding.embedding_dim
          - embedding.activation
          - gmm.n_kernels
          - gmm.n_samples
          - model
          - gamma
          - lr
          - batch_size
          - max_epochs
