[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "NCP"
dynamic = [
  "version"
]  
description = "Neural Conditional Probabilities" 
readme = "README.md"
requires-python = ">=3.9"

authors = [
  {name = "Pietro Novelli", email = "pietronvll@gmail.com" },
  {name = "Grégroire Pacreau", email = "gregoire.pacreau@polytechnique.edu"},
  {name = "Giacomo Turri", email = "giacomo.turri@iit.it"}
]
dependencies = [
  "torch>=2.0"
]

[project.optional-dependencies]
docs = [
  "sphinx",
  "sphinx-book-theme",
  "sphinx-design",
  "sphinxcontrib-bibtex",
  "sphinx-autobuild",
  "myst-nb"
]

[tool.hatch.version]
path = "NCP/__about__.py"

[tool.isort]
# make it compatible with black
profile = "black"