[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "NCP"
dynamic = [
  "version"
]  
description = "Neural Conditional Probabilities" 
readme = "README.md"
requires-python = ">=3.6"

authors = [

]
dependencies = [
  "torch"
]

[project.optional-dependencies]
docs = [
  "sphinx",
  "sphinx-book-theme",
  "sphinx-design",
  "sphinxcontrib-bibtex",
  "sphinx-autobuild",
  "myst-nb"
]

[tool.hatch.version]
path = "NCP/__about__.py"

[tool.isort]
# make it compatible with black
profile = "black"