[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "NCP"
dynamic = [
  "version"
]  
description = "Neural Conditional Probabilities" 
readme = "README.md"
requires-python = ">=3.6"

authors = [

]
dependencies = [
  "torch"
]

[project.optional-dependencies]
docs = [
  "sphinx",
  "sphinx-book-theme",
  "sphinx-design",
  "sphinxcontrib-bibtex",
  "sphinx-autobuild",
  "myst-nb"
]

[tool.hatch.version]
path = "NCP/__about__.py"

# RUFF ___________________________________________________________________________________________________________
[tool.ruff]
line-length = 120
select = [
  # pyflakes
  "F",
  # pycodestyle
  "E",
  "W",
  # isort
  "I001",
  # pydocstyle
  "D"
]
ignore = [
  "D401",  # good for methods but not for class docstrings
  "D405",  # British-style section names are also "proper"!
  "E701",  # short single-line statements are fine
  "D100",
]

exclude = [
  ".git",
  ".idea",
  ".venv",
]

[tool.ruff.pydocstyle]
convention = "google"
