_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 106
            "2":
                - 1
                - 5
                - 53
                - 55
                - 106
            "3":
                - 1
                - 7
                - 16
                - 23
                - 55
                - 66
            "4": 3.10.0
            "5": 0.19.1
            "8":
                - 1
                - 5
            "12": 0.19.1
            "13": linux-x86_64
embedding_dim:
    value: 6
gamma:
    value: 0.01
hidden_layers:
    value: 1
hidden_units:
    value: 64
irreps:
    value:
        - - 0
        - - 0
lr:
    value: 0.0001
