# Data loading
selection: 'backbone'
data_path: 'chignolin/data'
# NN configs
n_final_features: 16
n_atom_basis: 64
n_interactions: 3
n_rbf: 20
cutoff: 5.
# Training
batch_size: 256
lagtime: 20
max_epochs: 100
# Method
gamma: 1e-3
# Rng seed
seed: 0